#!/bin/bash

BASH_COMPLETION_DIR=/etc/bash_completion.d
BIN_DIR=/usr/local/bin
[ -d "$BASH_COMPLETION_DIR" ] && sudo install hecs_completions.sh "$BASH_COMPLETION_DIR"
[ -d "$BIN_DIR" ] && sudo install hecs "$BIN_DIR"
